### ISSUE TITLE
Error 400: invalid_request

### ISSUE THREAD

**Issue by mike-2545** [UniversalDevicesInc-PG3/holidays-google-poly#2]
Cannot set up link to google account

**Comment by Adam-B0mb** [comment]
I got the same issue:..  I click on the link provide in the config and then get this error:
Access blocked: Holidays Google Node Server’s request is invalid. 
You can’t sign in because Holidays Google Node Server sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Holidays Google Node Server, see [error details](https://accounts.google.com/).
Error 400: invalid_request

**Comment by firstone** [comment]
We're aware of the issue. Google has discontinued current authentication method. The fix is not trivial given polyglot/polisy backend centric architecture but it's being worked on. No ETA at this point, unfortunately.

**Comment by firstone** [comment]
I've posted a workaround in version 1.0.4 which requires to run authentication on desktop with a browser. Still working on a final fix.

**Comment by firstone** [comment]
Fixed in version 2.0.0 with pg3 version 3.1.18
